name: Generate GitHub Stats (Local)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Mr-Priyanshu-Gupta
          THEME: tokyonight

      - name: Push stats to stats branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: stats
          build_dir: profile-summary-card-output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
