name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate stats
        uses: anuraghazra/github-readme-stats@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          username: Mr-Priyanshu-Gupta
          theme: tokyonight
          show_icons: true
          hide_border: true
          output: dist/github-stats.svg

      - name: Push stats to repo
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: stats
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
