name: Generate GitHub Stats (Local)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: Mr-Priyanshu-Gupta
          AUTO_PUSH: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
